<a href="https://colab.research.google.com/github/krunalkatware/ML-TAE-1/blob/main/ML_TAE_1_Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [2]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [3]:
path = '/content/drive/MyDrive/MLDataset/diabetes.csv'
df = pd.read_csv(path)

In [4]:
df.head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [5]:
df.shape

(768, 9)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [7]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000


In [8]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [9]:
df.isnull().any().any()

np.False_

In [10]:
df.isnull().sum()

,0
Pregnancies,0
Glucose,0
BloodPressure,0
SkinThickness,0
Insulin,0
BMI,0
DiabetesPedigreeFunction,0
Age,0
Outcome,0


In [11]:
df[df.isnull().any(axis=1)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome


In [13]:
X = df.iloc[:,3:-1]
y = df['Outcome']

In [14]:
X.head()

,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,35,0,33.6,0.627,50
1,29,0,26.6,0.351,31
2,0,0,23.3,0.672,32
3,23,94,28.1,0.167,21
4,35,168,43.1,2.288,33


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y,train_size=0.7,random_state=42)

In [16]:
X_train.shape,X_test.shape

((537, 5), (231, 5))

In [17]:
X_train.head()

,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
334,18,58,23.9,0.260,22
139,29,325,36.9,0.159,28
485,42,250,42.3,0.365,24
547,21,166,33.1,0.160,28
18,38,83,43.3,0.183,33


In [18]:
from sklearn.preprocessing import StandardScaler
scaler  = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [19]:
X_train

array([[-0.15714558, -0.18973183, -1.06015343, -0.61421636, -0.94861028],
       [ 0.55361931,  2.13020339,  0.64646721, -0.90973787, -0.43466673],
       [ 1.39361417,  1.47853619,  1.35537117, -0.30699103, -0.77729576],
       ...,
       [ 1.07053923, -0.6936878 ,  1.78859026,  1.94892066,  0.42190587],
       [-1.3202154 , -0.6936878 ,  1.36849903, -0.77514391, -0.34900947],
       [-1.3202154 , -0.6936878 , -1.24394334, -0.60836445, -1.03426754]])

In [20]:
import tensorflow as tf

In [21]:
ann = tf.keras.models.Sequential()

In [22]:
ann.add(tf.keras.layers.Dense(units=9,activation='relu'))

In [23]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [24]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [25]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.4323 - loss: 0.8137
Epoch 2/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4248 - loss: 0.8011
Epoch 3/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5211 - loss: 0.7478
Epoch 4/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5210 - loss: 0.7405
Epoch 5/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5637 - loss: 0.7019
Epoch 6/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5960 - loss: 0.6902
Epoch 7/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6041 - loss: 0.6775
Epoch 8/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6434 - loss: 0.6358
Epoch 9/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6470 - loss: 0.6297
Epoch 10/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6604 - loss: 0.6101
Epoch 11/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6624 - loss: 0.5976
Epoch 12/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy

In [26]:
y_pred=ann.predict(X_test)
y_pred=(y_pred > 0.5)
y_pred

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step


array([[ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [28]:
cm=confusion_matrix(y_pred,y_test)
print(confusion_matrix(y_pred,y_test))

[[118  39]
 [ 33  41]]


In [29]:
print('Accuracy Score')
print(accuracy_score(y_pred,y_test))

Accuracy Score
0.6883116883116883


In [30]:
print('Classification Report')
print(classification_report(y_pred,y_test))

Classification Report
              precision    recall  f1-score   support

       False       0.78      0.75      0.77       157
        True       0.51      0.55      0.53        74

    accuracy                           0.69       231
   macro avg       0.65      0.65      0.65       231
weighted avg       0.70      0.69      0.69       231

